set(CMAKE_SYSTEM_NAME Dolly)
set(CMAKE_SYSTEM_PROCESSOR wasm64)
set(CMAKE_C_COMPILER /emsdk/upstream/emscripten/emcc)
set(CMAKE_CXX_COMPILER /emsdk/upstream/emscripten/em++)
set(CMAKE_AR /emsdk/upstream/bin/llvm-ar)
set(CMAKE_RANLIB /emsdk/upstream/bin/llvm-ranlib)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_FLAGS_INIT "-m64 -matomics -mbulk-memory -fwasm-exceptions -sWASM_LEGACY_EXCEPTIONS=0 -sSUPPORT_LONGJMP=wasm -I/src/include")
set(CMAKE_CXX_FLAGS_INIT "-m64 -matomics -mbulk-memory -fwasm-exceptions -sWASM_LEGACY_EXCEPTIONS=0 -sSUPPORT_LONGJMP=wasm -I/src/include")
set(CMAKE_FIND_ROOT_PATH /src/.cache/0ad/sysroot /emsdk/upstream/emscripten/cache/sysroot)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_MODULE_PATH /src/.cache/0ad/cmake)
