# Prints units.mk: the sources of the process sysroot's Emscripten libraries, as
# tools/system_libs.py at the pin selects them. Run in the pinned container:
#   podman run --rm -v "$PWD/demos/sysroot:/in:ro" IMAGE python3 /in/list-units.py > demos/sysroot/units.mk
import os, sys
sys.path.insert(0, '/emsdk/upstream/emscripten')
from tools import system_libs, utils
from tools.settings import settings

settings.MEMORY64 = 1
root = utils.path_from_root('system/lib')
libraries = {}
for cls in [system_libs.libc, system_libs.libmalloc, system_libs.libstandalonewasm, system_libs.libstubs]:
  for variation in cls.variations():
    library = cls(**variation)
    libraries[library.get_base_name()] = library

def units(name):
  library = libraries[name]
  library.build_dir = '/'
  flags = library.get_cflags()
  files = library.get_files()
  # The units libc compiles at -O2 instead of -Os (its libcalls).
  faster = {path for path in files if library.customize_build_cmd(list(flags), path) != flags}
  # A name that differs only by case from an earlier one gets a suffix, as in build_objects.
  seen, renamed = set(), set()
  for path in files:
    stem, count = utils.unsuffixed_basename(path), 0
    while (stem + (f'__{count}' if count else '')).lower() in seen:
      count += 1
    seen.add((stem + (f'__{count}' if count else '')).lower())
    if count:
      renamed.add(f'{os.path.relpath(path, root)}:{stem}__{count}.o')
  relative = lambda paths: {os.path.relpath(path, root) for path in paths}
  return relative(files), relative(faster), renamed

def variable(name, paths, prefix=''):
  paths = sorted(paths)
  rows = [' '.join(paths[at:at + 6]) for at in range(0, len(paths), 6)]
  print(f'{name} := {prefix}' + ' \\\n  '.join(rows))

print('# Generated by list-units.py from Emscripten 6.0.8 tools/system_libs.py; paths are under system/lib.')
ww, ww_faster, renamed = units('libc-ww')
mt, mt_faster, mt_renamed = units('libc-mt')
variable('libc', ww & mt)
variable('libc-ww', ww - mt, '$(libc) ')
variable('libc-mt', mt - ww, '$(libc) ')
variable('O2', ww_faster | mt_faster)
variable('renamed', renamed | mt_renamed)
for name in ['libdlmalloc-ww', 'libdlmalloc-mt', 'libstandalonewasm-ww-memgrow', 'libstandalonewasm-mt-memgrow', 'libstubs']:
  files, faster, renamed = units(name)
  assert not faster and not renamed
  variable(name, files)
