DOLLY 3
MODULE sdl2

REQUIRES HEADER libc
REQUIRES HEADER display
REQUIRES TOOL cc
REQUIRES TOOL cmake
REQUIRES TOOL make
REQUIRES TOOL tar
REQUIRES TOOL rm

SOURCE HOST /static/sdl2/source.tar /tmp/sdl2/source.tar 0e9ff8962345c781cec332529a4f536729939274f13cbbab9fab0d762cf00d9c
SLOP tar -xf /tmp/sdl2/source.tar -C /
SLOP cmake -S /tmp/sdl2/source -B /tmp/sdl2/build \
  -DCMAKE_SYSTEM_NAME=Dolly -DCMAKE_SYSTEM_PROCESSOR=wasm64 \
  -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE=Release '-DCMAKE_C_FLAGS=-DDOLLY -U__EMSCRIPTEN__' -DCMAKE_C_FLAGS_RELEASE=-O1 \
  -DSDL_SHARED=OFF -DSDL_STATIC=ON -DSDL_TEST=OFF -DSDL_TESTS=OFF \
  -DSDL_AUDIO=OFF -DSDL_JOYSTICK=OFF -DSDL_HAPTIC=OFF -DSDL_SENSOR=OFF \
  -DSDL_THREADS=OFF -DSDL_LOADSO=OFF -DSDL_POWER=OFF -DSDL_HIDAPI=OFF \
  -DSDL_ASSEMBLY=OFF -DSDL_GCC_ATOMICS=ON -DSDL_SYSTEM_ICONV=OFF \
  -DSDL_OPENGL=OFF -DSDL_OPENGLES=OFF -DSDL_VULKAN=OFF -DSDL_RENDER_METAL=OFF
SLOP cmake --build /tmp/sdl2/build
SLOP cmake --install /tmp/sdl2/build

EXPORTS HEADER sdl2 /usr/include/SDL2
EXPORTS LIB SDL2 /usr/lib/libSDL2.a
EXPORTS FOLDER sdl2-cmake /usr/lib/cmake/SDL2
FILE /usr/share/licenses/SDL2/LICENSE.txt
SLOP rm -rf /tmp/sdl2
