/* Generated from host/audio/dolly-audio-0.wat. */
#pragma once
#define DOLLY_AUDIO_VERSION 0u
#define DOLLY_AUDIO_PROCESS_OP 129u
#define DOLLY_AUDIO_SLOTS 4u
#define DOLLY_AUDIO_REPLY_BYTES 16u
#define DOLLY_AUDIO_PACKET_BYTES 32808u
#define DOLLY_AUDIO_RATE 48000u
#define DOLLY_AUDIO_CHANNELS 2u
#define DOLLY_AUDIO_MIN_FRAMES 128u
#define DOLLY_AUDIO_MAX_FRAMES 4096u
#define DOLLY_AUDIO_QUEUE_FRAMES 48000u
#define DOLLY_AUDIO_MAX_BUFFERS 64u
#define DOLLY_AUDIO_OPEN 1u
#define DOLLY_AUDIO_WRITE 2u
#define DOLLY_AUDIO_STATUS 3u
#define DOLLY_AUDIO_CLOSE 4u
