/* SPDX-License-Identifier: MIT */
#ifndef DOLLY_CLASSICUBE_CONFIG_H
#define DOLLY_CLASSICUBE_CONFIG_H
#define CC_BUILD_MANUAL
#define CC_BUILD_POSIX
#define CC_BUILD_COOPTHREADED
#define CC_BUILD_NOMUSIC
#define CC_BUILD_NOSOUNDS
#define CC_WIN_BACKEND CC_WIN_BACKEND_SDL2
#define CC_GFX_BACKEND CC_GFX_BACKEND_SOFTGPU
#define CC_AUD_BACKEND CC_AUD_BACKEND_NULL
#define CC_NET_BACKEND CC_NET_BACKEND_BUILTIN
#define CC_SSL_BACKEND CC_SSL_BACKEND_NONE
#include "Core.h"
#undef CC_BUILD_NETWORKING
#undef CC_BUILD_FREETYPE
#undef CC_BUILD_RESOURCES
#undef CC_BUILD_PLUGINS
#undef CUSTOM_MODELS
#endif
