/* SPDX-License-Identifier: MIT */
/* What configure would find on Dolly, once for GLib, ATK, Pango, GTK+, libart and GIMP; each
 * library's own names (its gettext domain, version and directories) are -D flags in Makefile.in. */
#define G_COMPILED_WITH_DEBUGGING "minimum"
#define G_THREAD_SOURCE "gthread-none.c"
#define GLIB_SIZEOF_SYSTEM_THREAD 8
#define GLIB_BINARY_AGE 606
#define GLIB_INTERFACE_AGE 6
#define G_VA_COPY va_copy
#define G_HAVE_INLINE 1
#define G_HAVE___INLINE 1
#define G_HAVE___INLINE__ 1

#define STDC_HEADERS 1
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_DIRENT_H 1
#define HAVE_FLOAT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_INTTYPES_H_WITH_UINTMAX 1
#define HAVE_LANGINFO_H 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_MEMORY_H 1
#define HAVE_PWD_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDINT_H_WITH_UINTMAX 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_POLL_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIMES_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_VALUES_H 1

#define HAVE_ATEXIT 1
#define HAVE_C99_SNPRINTF 1
#define HAVE_C99_VSNPRINTF 1
#define HAVE_CODESET 1
#define HAVE_GETCWD 1
#define HAVE_GETC_UNLOCKED 1
#define HAVE_GOOD_PRINTF 1
#define HAVE_INTMAX_T 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_LC_MESSAGES 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LONG_DOUBLE 1
#define HAVE_LONG_LONG 1
#define HAVE_LONG_LONG_FORMAT 1
#define HAVE_LSTAT 1
#define HAVE_MEMMOVE 1
#define HAVE_MKSTEMP 1
#define HAVE_NANOSLEEP 1
#define HAVE_NL_LANGINFO 1
#define HAVE_POLL 1
#define HAVE_POSIX_GETPWUID_R 1
#define HAVE_PTRDIFF_T 1
#define HAVE_READLINK 1
#define HAVE_SETENV 1
#define HAVE_SETLOCALE 1
#define HAVE_SNPRINTF 1
#define HAVE_STPCPY 1
#define HAVE_STRCASECMP 1
#define HAVE_STRERROR 1
#define HAVE_STRNCASECMP 1
#define HAVE_STRSIGNAL 1
#define HAVE_SYMLINK 1
#define HAVE_UNIX98_PRINTF 1
#define HAVE_UNSETENV 1
#define HAVE_VASPRINTF 1
#define HAVE_VPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_WCHAR_T 1
#define HAVE_WINT_T 1
#define NO_SYS_ERRLIST 1
#define NO_SYS_SIGLIST 1
#define NO_SYS_SIGLIST_DECL 1
#define REALLOC_0_WORKS 1
#define SANE_MALLOC_PROTOS 1
#define SIZEOF_CHAR 1
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_VOID_P 8
#define SIZEOF___INT64 0
