#!/usr/bin/env bash
# Prints the directory of the prepared NetSurf tree: the browser and the libraries
# of its pinned release that the Wine demo builds, with netsurf-dolly.patch applied
# and the sources its makefiles generate with perl, gperf and a C tool generated here.
set -euo pipefail
project_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
source "${project_dir}/config/source-pins.sh"
demo_dir="${project_dir}/demos/wine"
libraries=(libwapcaplet libparserutils libhubbub libdom libcss libnsbmp libnsgif libnsutils libutf8proc libnspsl)
archive="$("${project_dir}/scripts/fetch-verified-file.sh" "${DOLLY_NETSURF_URL}" "${DOLLY_NETSURF_SHA256}" \
  "${project_dir}/.cache/netsurf-all-${DOLLY_NETSURF_VERSION}.tar.gz")"
gperf="$(bash "${demo_dir}/build-gperf.sh")"
recipe_hash="$(sha256sum "${demo_dir}/netsurf-dolly.patch" "${BASH_SOURCE[0]}" | sha256sum | cut -d' ' -f1)"
output="${project_dir}/build/generated/netsurf-${DOLLY_NETSURF_VERSION}-${recipe_hash:0:16}"
if [[ ! -d "${output}" ]]; then
  mkdir -p "${project_dir}/build/generated"
  temporary="$(mktemp -d "${project_dir}/build/generated/.netsurf.XXXXXX")"
  trap 'rm -rf -- "${temporary}"' EXIT
  mkdir "${temporary}/full" "${temporary}/tree"
  tar -xzf "${archive}" --strip-components=1 -C "${temporary}/full"
  [[ ! -s "${demo_dir}/netsurf-dolly.patch" ]] || patch --silent --fuzz=0 --no-backup-if-mismatch -d "${temporary}/full" -p1 < "${demo_dir}/netsurf-dolly.patch"
  (cd "${temporary}/full/libparserutils" && perl build/make-aliases.pl)
  # libdom's makefile installs its hubbub binding's headers among the public ones.
  mkdir -p "${temporary}/full/libdom/include/dom/bindings/hubbub"
  cp "${temporary}/full/libdom/bindings/hubbub/"{parser,errors}.h "${temporary}/full/libdom/include/dom/bindings/hubbub/"
  (cd "${temporary}/full/libhubbub" && perl build/make-entities.pl &&
    "${gperf}" src/treebuilder/element-type.gperf |
      sed -e 's/^\(const struct element_type_map\)/static \1/' > src/treebuilder/autogenerated-element-type.c)
  # libcss: one parser per line of properties.gen that names a property.
  (cd "${temporary}/full/libcss/src/parse/properties" && cc -O1 -o gen_parser css_property_parser_gen.c &&
    grep '^[^#][^:]*:' properties.gen | while IFS= read -r property; do
      ./gen_parser -o "autogenerated_${property%%:*}.c" "${property}"
    done && rm gen_parser)
  # NetSurf: the messages of the Windows front end's five languages, as its resource file names them.
  (cd "${temporary}/full/netsurf" && for language in de en fr it nl; do
    mkdir -p "frontends/windows/res/${language}"
    perl tools/split-messages.pl -l "${language}" -p win -f messages -z \
      -o "frontends/windows/res/${language}/Messages" resources/FatMessages
  done)
  # What git-testament.pl writes for a tarball, without this host's user, name and date.
  cat > "${temporary}/full/netsurf/testament.h" <<'TESTAMENT'
#define USERNAME "dolly"
#define GECOS "Dolly"
#define WT_ROOT "/usr/src/dolly/wine/programs/netsurf/"
#define WT_HOSTNAME "dolly"
#define WT_COMPILEDATE "the 3.11 release"
#define WT_BRANCHPATH "tarball"
#define WT_NO_GIT 1
#define WT_REVID "unknown"
#define WT_MODIFIED 0
#define WT_MODIFICATIONS { }
TESTAMENT
  # Not built: tests, documentation, the JavaScript engine, the other front ends (whose links to generated files dangle).
  rm -rf -- "${temporary}/full/netsurf/content/handlers/javascript/duktape"
  find "${temporary}/full" -depth -type d \( -name test -o -name tests -o -name docs -o -name examples -o -name testdata \) -exec rm -rf {} +
  for frontend in "${temporary}/full/netsurf/frontends"/*/; do
    [[ "$(basename "${frontend}")" == windows ]] || rm -rf -- "${frontend}"
  done
  for path in "${libraries[@]}" netsurf; do cp -aL "${temporary}/full/${path}" "${temporary}/tree/${path}"; done
  mv -T -- "${temporary}/tree" "${output}"
fi
printf '%s\n' "${output}"
