// SPDX-License-Identifier: GPL-2.0-or-later
export function relayProvider(config) {
  const provider = config?.providers?.["codex-local"];
  const url = new URL(provider?.baseUrl ?? "invalid:");
  if (url.protocol !== "http:" || !["localhost", "127.0.0.1"].includes(url.hostname) ||
      url.username || url.password || url.pathname !== "/" || url.search || url.hash ||
      provider?.api !== "openai-codex-responses" || typeof provider.apiKey !== "string" ||
      !provider.apiKey || provider.apiKey.startsWith("!") || !Array.isArray(provider.models) ||
      !provider.models.length || provider.models.some(model => typeof model.id !== "string" ||
        !model.id || !model.input?.includes("image")))
    throw Error("Choose the models.json generated by scripts/codex-relay.mjs, not Codex auth.json");
  // Do not import arbitrary provider/auth commands from an uploaded configuration.
  return { api: provider.api, baseUrl: provider.baseUrl, apiKey: provider.apiKey,
    models: provider.models.map(({ id, name, reasoning, input, cost, contextWindow, maxTokens, thinkingLevelMap }) =>
      ({ id, name, reasoning, input, cost, contextWindow, maxTokens, thinkingLevelMap })) };
}

export async function importRelay(fs, run, directory) {
  const temporary = fs.mkdtempSync("/tmp/codex-relay-import-");
  try {
    const path = `${temporary}/models.json`;
    if (await run("upload", [path]) !== 0) return false;
    let provider;
    try { provider = relayProvider(JSON.parse(fs.readFileSync(path, "utf8"))); }
    catch { throw Error("Choose the models.json generated by scripts/codex-relay.mjs, not native auth.json"); }
    fs.mkdirSync(directory, { recursive: true });
    const configPath = `${directory}/models.json`;
    const config = fs.existsSync(configPath) ? JSON.parse(fs.readFileSync(configPath, "utf8")) : {};
    config.providers = { ...config.providers, "codex-local": provider };
    const merged = `${temporary}/merged.json`;
    fs.writeFileSync(merged, JSON.stringify(config) + "\n");
    fs.renameSync(merged, configPath);
    return true;
  } finally { fs.rmSync(temporary, { recursive: true, force: true }); }
}
