// Generated from host/snapshot/dolly-snapshot-0.wat.
export const DOLLY_SESSION_HEADER_SIZE = 64;
export const DOLLY_SESSION_NAME_CAPACITY = 128;
export const DOLLY_SESSION_TRANSFER_CAPACITY = 1048576;
export const DOLLY_SESSION_WORD_REQUEST_SEQUENCE = 0;
export const DOLLY_SESSION_WORD_COMPLETED_SEQUENCE = 1;
export const DOLLY_SESSION_WORD_STATUS = 2;
export const DOLLY_SESSION_WORD_NAME_LENGTH = 3;
export const DOLLY_SESSION_WORD_CHUNK_SEQUENCE = 4;
export const DOLLY_SESSION_WORD_CHUNK_CONSUMED_SEQUENCE = 5;
export const DOLLY_SESSION_WORD_CHUNK_LENGTH = 6;
export const DOLLY_SESSION_WORD_CHUNK_EOF = 7;
export const DOLLY_SESSION_WORD_TOTAL_SIZE_LOW = 8;
export const DOLLY_SESSION_WORD_TOTAL_SIZE_HIGH = 9;
export const DOLLY_SESSION_WORD_CANCELLED_SEQUENCE = 10;
