(module
  ;; Typed internal boundary used by the trusted runtime Worker to schedule
  ;; private process Workers. Filesystem and process semantics remain in the
  ;; kernel Wasm implementation behind these operations.
  (func $version (result i32) i32.const 0)
  (func $mailbox_address (result i64) i64.const 0)
  (func $mailbox_capacity (result i64) i64.const 0)
  (func $spawn_serialized (param i64) (result i32) i32.const 0)
  (func $dispatch (param i32 i32 i64 i64) (result i64) i64.const 0)
  (func $next_launch (result i32) i32.const 0)
  (func $image_address (param i32) (result i64) i64.const 0)
  (func $image_size (param i32) (result i64) i64.const 0)
  (func $image_consumed (param i32) (result i32) i32.const 0)
  (func $worker_started (param i32) (result i32) i32.const 0)
  (func $worker_failed (param i32 i32) (result i32) i32.const 0)
  (func $signal (param i32 i32) (result i32) i32.const 0)
  (func $deadline_remaining (param i32) (result f64) f64.const -1)
  (func $collect (param i32) (result i32) i32.const 0)
  (func $parent (param i32) (result i32) i32.const 0)

  (export "dolly_process_supervisor_version" (func $version))
  (export "dolly_process_mailbox_address" (func $mailbox_address))
  (export "dolly_process_mailbox_capacity" (func $mailbox_capacity))
  (export "dolly_process_spawn_serialized" (func $spawn_serialized))
  (export "dolly_process_dispatch" (func $dispatch))
  (export "dolly_process_next_launch" (func $next_launch))
  (export "dolly_process_image_address" (func $image_address))
  (export "dolly_process_image_size" (func $image_size))
  (export "dolly_process_image_consumed" (func $image_consumed))
  (export "dolly_process_worker_started" (func $worker_started))
  (export "dolly_process_worker_failed" (func $worker_failed))
  (export "dolly_process_signal" (func $signal))
  (export "dolly_process_deadline_remaining" (func $deadline_remaining))
  (export "dolly_process_collect" (func $collect))
  (export "dolly_process_parent" (func $parent))
)
